### ISSUE TITLE
Slow performance for multiples in Firefox

### ISSUE THREAD

**Issue by UNFPAmaldives** [PatMartin/Dex#12]
Having adapted one of the examples on dexvis.net, multiple c3 area charts are loading from a large dataset much more slowly in Firefox versus Chrome  (57 seconds, versus 16 seconds)

**Comment by PatMartin** [comment]
Try generating them again with the latest Dex from github.  At work I had datasets which were in the millions of items and had to spend a few weeks in Chrome DevTools tuning javascript memory usage.  The performance of the generating assets are orders of magnitude better for larger datasets.   Since you're using multiples, I assume your data is largish.

I believe and hope that you may see a drastic difference now, though I am not sure why FF is so different for you.  If your issues persist, then let me know and we can go from there.

- Pat

**Comment by PatMartin** [comment]
With memory fixes, good FF performance now.  Closing issue.
